/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Text;
export const CommentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'comments' : IDL.Vec(Comment),
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [PostId], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getNewsFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'login' : IDL.Func([], [UserProfile], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Text;
  const CommentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'comments' : IDL.Vec(Comment),
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [PostId], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getNewsFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'login' : IDL.Func([], [UserProfile], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };